### ISSUE TITLE
Need opposite function: Convert Unix Timestamp to RFC 2822 timestamp

### ISSUE THREAD

**Issue by tobwz** [henrypp/timevertor#2]
As far as I can see TimeVertor offers only a conversion in one direction FROM RFC 2822 to others.

Occasionally I need the opposite conversion particularly from
UNIX timestamp to RFC 2822

Can you add this feature?

Thank you

**Comment by henrypp** [comment]
Datetime input is editable, so you can insert unixtime into it and press Enter and get RFC 2822.
